const fs = require('fs');
const path = require('path');
const { hydrate, sync } = require('./persistentStore');

const DATA_DIR = process.env.DATA_DIR || path.join(__dirname, 'data');
const DB_FILE = path.join(DATA_DIR, 'tournament-details.json');
const SHEET_KEY = 'tournamentDetails';

// Stored as a map:
//   { [tournamentId]: { teams: [...], matches: [...], settings: {...} } }

const ROLES = ['Exp', 'Jungle', 'Mid', 'Gold', 'Roam', 'Coach', 'Manager', 'Sub'];
const TEAM_STATUSES = ['invited', 'qualified', 'open_qualifier'];
// A team's group-stage pool. '' means not assigned to either group yet.
const TEAM_GROUPS = ['', 'A', 'B'];
// Bracket slot ids are generated by the client from the chosen format
// (e.g. "s-r0-m3", "d-lb1-m0", "d-gf", "s-3rd"), so they are validated by
// shape rather than against a fixed list.
const BRACKET_SLOT_RE = /^[a-z0-9-]{1,24}$/;
const TAB_KEYS = ['regteams', 'confirmed', 'qualifier', 'lineup', 'schedule', 'standings', 'bracket'];
// The qualifier is a single-elimination BO1 draw run separately per region.
const QUALIFIER_REGIONS = ['MM', 'TH'];
const QUALIFIER_SIZES = [32, 64, 128];
const BO_OPTIONS = [1, 3, 5, 7];

function ensureFile() {
  if (!fs.existsSync(path.dirname(DB_FILE))) {
    fs.mkdirSync(path.dirname(DB_FILE), { recursive: true });
  }
  if (!fs.existsSync(DB_FILE)) {
    fs.writeFileSync(DB_FILE, '{}', 'utf8');
  }
}

function readAll() {
  ensureFile();
  try {
    return JSON.parse(fs.readFileSync(DB_FILE, 'utf8'));
  } catch (e) {
    return {};
  }
}

function writeAll(map) {
  ensureFile();
  fs.writeFileSync(DB_FILE, JSON.stringify(map, null, 2), 'utf8');
  sync(SHEET_KEY, map);
}

function defaultQualifier() {
  return { MM: 32, TH: 32 };
}

function defaultSettings() {
  return {
    hiddenTabs: [], bracketType: 'single', bracketSize: 8, thirdPlace: true,
    qualifierSize: defaultQualifier(),
  };
}

// Admin-controlled display settings: which detail sections the public can see,
// and how the bracket is shaped.
function cleanSettings(s) {
  if (!s || typeof s !== 'object') return defaultSettings();
  const bracketType = s.bracketType === 'double' ? 'double' : 'single';
  const allowedSizes = bracketType === 'double' ? [4, 8] : [4, 8, 16];
  const size = Number(s.bracketSize);
  // Per-region qualifier bracket size (32 / 64 / 128).
  const qs = (s.qualifierSize && typeof s.qualifierSize === 'object') ? s.qualifierSize : {};
  const qualifierSize = {};
  QUALIFIER_REGIONS.forEach((r) => {
    const n = Number(qs[r]);
    qualifierSize[r] = QUALIFIER_SIZES.includes(n) ? n : 32;
  });
  return {
    hiddenTabs: Array.isArray(s.hiddenTabs)
      ? [...new Set(s.hiddenTabs.filter((k) => TAB_KEYS.includes(k)))]
      : [],
    bracketType,
    bracketSize: allowedSizes.includes(size) ? size : 8,
    thirdPlace: s.thirdPlace !== false,
    qualifierSize,
  };
}

function emptyDetail() {
  return { teams: [], matches: [], settings: defaultSettings() };
}

function genId(prefix) {
  return prefix + '-' + Date.now().toString(36) + '-' + Math.floor(Math.random() * 1000);
}

function cleanPlayer(p) {
  return {
    id: p.id || genId('P'),
    name: String(p.name || '').trim().slice(0, 40),
    role: ROLES.includes(p.role) ? p.role : 'Sub',
  };
}

function cleanTeam(t) {
  return {
    id: t.id || genId('T'),
    name: String(t.name || '').trim().slice(0, 60),
    tag: String(t.tag || '').trim().slice(0, 10),
    logo: t.logo ? String(t.logo) : '', // data URL, optional
    status: TEAM_STATUSES.includes(t.status) ? t.status : 'invited',
    group: TEAM_GROUPS.includes(t.group) ? t.group : '',
    players: Array.isArray(t.players) ? t.players.map(cleanPlayer) : [],
  };
}

// An unplayed match has no score at all. Number(null) is 0 and Number('') is
// 0, both of which pass Number.isFinite — so blanks have to be rejected
// before the numeric check, or every unscored match would be saved as 0-0.
function cleanScore(v) {
  if (v === null || v === undefined || v === '') return null;
  return Number.isFinite(Number(v)) ? Number(v) : null;
}

function cleanMatch(m) {
  const stage = m.stage === 'bracket' ? 'bracket' : 'group';
  const base = {
    id: m.id || genId('M'),
    stage,
    teamAId: m.teamAId || '',
    teamBId: m.teamBId || '',
    scoreA: cleanScore(m.scoreA),
    scoreB: cleanScore(m.scoreB),
    status: ['upcoming', 'live', 'completed'].includes(m.status) ? m.status : 'upcoming',
    scheduledAt: String(m.scheduledAt || '').trim(),
    bestOf: BO_OPTIONS.includes(Number(m.bestOf)) ? Number(m.bestOf) : 3,
    votes: { a: Number(m.votes && m.votes.a) || 0, b: Number(m.votes && m.votes.b) || 0 },
  };
  if (stage === 'group') {
    return {
      ...base,
      group: m.group === 'B' ? 'B' : 'A',
      day: String(m.day || 'Day 1').trim().slice(0, 30),
    };
  }
  const slot = String(m.bracketSlot || '');
  return {
    ...base,
    bracketSlot: BRACKET_SLOT_RE.test(slot) ? slot : 's-r0-m0',
  };
}

function getDetail(tournamentId) {
  const all = readAll();
  const d = all[tournamentId];
  if (!d) return emptyDetail();
  return { ...d, settings: cleanSettings(d.settings) };
}

function saveDetail(tournamentId, data) {
  const all = readAll();
  // Bracket matches are keyed by slot — only one match per slot allowed.
  const bracketSeen = new Set();
  const cleanMatches = (Array.isArray(data.matches) ? data.matches : [])
    .map(cleanMatch)
    .filter((m) => {
      if (m.stage !== 'bracket') return true;
      if (bracketSeen.has(m.bracketSlot)) return false;
      bracketSeen.add(m.bracketSlot);
      return true;
    });
  const clean = {
    teams: Array.isArray(data.teams) ? data.teams.map(cleanTeam) : [],
    matches: cleanMatches,
    // Keep whatever was already stored if this request didn't send settings.
    settings: cleanSettings(
      data.settings !== undefined ? data.settings : (all[tournamentId] || {}).settings
    ),
  };
  all[tournamentId] = clean;
  writeAll(all);
  return clean;
}

function deleteDetail(tournamentId) {
  const all = readAll();
  if (!(tournamentId in all)) return false;
  delete all[tournamentId];
  writeAll(all);
  return true;
}

function vote(tournamentId, matchId, side) {
  const all = readAll();
  const detail = all[tournamentId];
  if (!detail) return null;
  const m = detail.matches.find((x) => x.id === matchId);
  if (!m) return null;
  if (!m.votes) m.votes = { a: 0, b: 0 };
  if (side === 'a') m.votes.a++;
  else if (side === 'b') m.votes.b++;
  else return null;
  writeAll(all);
  return m.votes;
}

// Derives Group A / Group B standings from completed group-stage matches —
// admins enter match results, never standings directly, so this can never
// drift out of sync with the actual scores. Sort order matches typical
// esports group tiebreakers: match points, then net game win, then game wins.
// Points for a completed match. A clean sweep (the loser takes no games) is
// worth more than a win that went the distance:
//   2-0 -> winner 3, loser 0
//   2-1 -> winner 2, loser 1
// Expressed in terms of the loser's game count so it holds for Bo5/Bo7 too
// (3-0 -> 3/0, while 3-1 and 3-2 -> 2/1).
function pointsFor(winnerGames, loserGames) {
  return loserGames === 0 ? { winner: 3, loser: 0 } : { winner: 2, loser: 1 };
}

// Which group a match counts towards. Team assignments from the lineup are
// authoritative — the match's own group field is only a fallback for matches
// created before the two teams were sorted into pools.
function groupOfMatch(m, teamsById) {
  const ga = (teamsById[m.teamAId] || {}).group;
  const gb = (teamsById[m.teamBId] || {}).group;
  if (ga && ga === gb) return ga;
  if (m.group === 'A' || m.group === 'B') return m.group;
  return null;
}

function computeStandings(detail) {
  const table = { A: {}, B: {} };
  const teamsById = {};
  detail.teams.forEach((tm) => { teamsById[tm.id] = tm; });

  function ensureRow(g, teamId) {
    if (!table[g][teamId]) {
      table[g][teamId] = { matchWins: 0, matchLosses: 0, gameWins: 0, gameLosses: 0, points: 0 };
    }
    return table[g][teamId];
  }

  // Seed every assigned team first, so a team shows up in its group's table
  // as soon as it's assigned — on zero points, before it has played anything.
  detail.teams.forEach((tm) => {
    if (tm.group === 'A' || tm.group === 'B') ensureRow(tm.group, tm.id);
  });

  detail.matches
    .filter((m) => m.stage === 'group' && m.status === 'completed'
      && m.scoreA !== null && m.scoreB !== null && m.scoreA !== m.scoreB
      && m.teamAId && m.teamBId)
    .forEach((m) => {
      const g = groupOfMatch(m, teamsById);
      if (!g) return;
      const rowA = ensureRow(g, m.teamAId);
      const rowB = ensureRow(g, m.teamBId);
      rowA.gameWins += m.scoreA; rowA.gameLosses += m.scoreB;
      rowB.gameWins += m.scoreB; rowB.gameLosses += m.scoreA;
      const aWon = m.scoreA > m.scoreB;
      const pts = aWon ? pointsFor(m.scoreA, m.scoreB) : pointsFor(m.scoreB, m.scoreA);
      if (aWon) {
        rowA.matchWins++; rowB.matchLosses++;
        rowA.points += pts.winner; rowB.points += pts.loser;
      } else {
        rowB.matchWins++; rowA.matchLosses++;
        rowB.points += pts.winner; rowA.points += pts.loser;
      }
    });

  const result = { A: [], B: [] };
  ['A', 'B'].forEach((g) => {
    result[g] = Object.keys(table[g])
      .map((teamId) => {
        const r = table[g][teamId];
        return {
          team: teamsById[teamId] || { id: teamId, name: 'Unknown', tag: '' },
          matchWins: r.matchWins,
          matchLosses: r.matchLosses,
          matchPoints: r.points,
          gameWins: r.gameWins,
          gameLosses: r.gameLosses,
          netGameWin: r.gameWins - r.gameLosses,
        };
      })
      .sort((a, b) => b.matchPoints - a.matchPoints || b.netGameWin - a.netGameWin || b.gameWins - a.gameWins);
  });
  return result;
}

// For bracket UX: figure out the winner/loser team of a given slot (if that
// match has been played), so the next slot's team dropdowns can be
// pre-filled automatically instead of the admin re-picking from scratch.
function getBracketOutcome(detail, slot) {
  const m = detail.matches.find((x) => x.stage === 'bracket' && x.bracketSlot === slot);
  if (!m || m.scoreA === null || m.scoreB === null || m.scoreA === m.scoreB) return { winner: null, loser: null };
  return m.scoreA > m.scoreB
    ? { winner: m.teamAId, loser: m.teamBId }
    : { winner: m.teamBId, loser: m.teamAId };
}

const ready = hydrate(SHEET_KEY, DB_FILE);

module.exports = {
  getDetail, saveDetail, deleteDetail, computeStandings, vote, getBracketOutcome,
  cleanSettings, defaultSettings,
  pointsFor,
  ROLES, TEAM_STATUSES, TEAM_GROUPS, TAB_KEYS, BO_OPTIONS,
  QUALIFIER_REGIONS, QUALIFIER_SIZES, ready,
};
